apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-deployment
  labels:
    app: pod-info
spec:
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      containers:
      - name: pod-info-test
        image: pod-info-test
